### ISSUE TITLE
thread 'main' panicked at library\alloc\src\raw_vec.rs:25:5:

### ISSUE THREAD

**Issue by h0medev2024** [austinleroy/uasset-data-parser#1]
thread 'main' panicked at library\alloc\src\raw_vec.rs:25:5:
capacity overflow

Open UE4.27.1 uasset file error

**Comment by austinleroy** [comment]
Do you have a longer stack trace or the example file?  That panic is inside a core allocation method

**Comment by austinleroy** [comment]
Without being able to reproduce, not much to do here
